/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContinueRouteImport } from './routes/continue'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MyListRouteImport } from './routes/my-list'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as AdminSourcesRouteImport } from './routes/admin.sources'
import { Route as MovieIdRouteImport } from './routes/movie.$id'
import { Route as RemoteIndexRouteImport } from './routes/remote.index'
import { Route as RemoteCodeRouteImport } from './routes/remote.$code'
import { Route as ShowIdRouteImport } from './routes/show.$id'
import { Route as WatchTypeIdRouteImport } from './routes/watch.$type.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContinueRoute = ContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyListRoute = MyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIdRoute = MovieIdRouteImport.update({
  id: '/movie/$id',
  path: '/movie/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteIndexRoute = RemoteIndexRouteImport.update({
  id: '/remote/',
  path: '/remote/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteCodeRoute = RemoteCodeRouteImport.update({
  id: '/remote/$code',
  path: '/remote/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowIdRoute = ShowIdRouteImport.update({
  id: '/show/$id',
  path: '/show/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchTypeIdRoute = WatchTypeIdRouteImport.update({
  id: '/watch/$type/$id',
  path: '/watch/$type/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/continue': typeof ContinueRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/movie/$id': typeof MovieIdRoute
  '/remote/$code': typeof RemoteCodeRoute
  '/show/$id': typeof ShowIdRoute
  '/remote/': typeof RemoteIndexRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/continue': typeof ContinueRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/movie/$id': typeof MovieIdRoute
  '/remote/$code': typeof RemoteCodeRoute
  '/show/$id': typeof ShowIdRoute
  '/remote': typeof RemoteIndexRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/continue': typeof ContinueRoute
  '/history': typeof HistoryRoute
  '/movies': typeof MoviesRoute
  '/my-list': typeof MyListRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shows': typeof ShowsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/movie/$id': typeof MovieIdRoute
  '/remote/$code': typeof RemoteCodeRoute
  '/show/$id': typeof ShowIdRoute
  '/remote/': typeof RemoteIndexRoute
  '/watch/$type/$id': typeof WatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/continue'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/shows'
    | '/admin/sources'
    | '/movie/$id'
    | '/remote/$code'
    | '/show/$id'
    | '/remote/'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/continue'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/shows'
    | '/admin/sources'
    | '/movie/$id'
    | '/remote/$code'
    | '/show/$id'
    | '/remote'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/'
    | '/continue'
    | '/history'
    | '/movies'
    | '/my-list'
    | '/search'
    | '/settings'
    | '/shows'
    | '/admin/sources'
    | '/movie/$id'
    | '/remote/$code'
    | '/show/$id'
    | '/remote/'
    | '/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContinueRoute: typeof ContinueRoute
  HistoryRoute: typeof HistoryRoute
  MoviesRoute: typeof MoviesRoute
  MyListRoute: typeof MyListRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShowsRoute: typeof ShowsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  MovieIdRoute: typeof MovieIdRoute
  RemoteCodeRoute: typeof RemoteCodeRoute
  ShowIdRoute: typeof ShowIdRoute
  RemoteIndexRoute: typeof RemoteIndexRoute
  WatchTypeIdRoute: typeof WatchTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/continue': {
      id: '/continue'
      path: '/continue'
      fullPath: '/continue'
      preLoaderRoute: typeof ContinueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-list': {
      id: '/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof MyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$id': {
      id: '/movie/$id'
      path: '/movie/$id'
      fullPath: '/movie/$id'
      preLoaderRoute: typeof MovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/': {
      id: '/remote/'
      path: '/remote'
      fullPath: '/remote/'
      preLoaderRoute: typeof RemoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote/$code': {
      id: '/remote/$code'
      path: '/remote/$code'
      fullPath: '/remote/$code'
      preLoaderRoute: typeof RemoteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show/$id': {
      id: '/show/$id'
      path: '/show/$id'
      fullPath: '/show/$id'
      preLoaderRoute: typeof ShowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$type/$id': {
      id: '/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof WatchTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContinueRoute: ContinueRoute,
  HistoryRoute: HistoryRoute,
  MoviesRoute: MoviesRoute,
  MyListRoute: MyListRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShowsRoute: ShowsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  MovieIdRoute: MovieIdRoute,
  RemoteCodeRoute: RemoteCodeRoute,
  ShowIdRoute: ShowIdRoute,
  RemoteIndexRoute: RemoteIndexRoute,
  WatchTypeIdRoute: WatchTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
